### ISSUE TITLE
YouTubePlayerView initialise error : SERVICE_MISSING

### ISSUE THREAD

**Issue by 0x12Jung** [PRNDcompany/YouTubePlayerView#12]
Hi all, yesterday I use this player and got the error hint "error when initial You Tube Player" on the YouTubePlayerView screen, but few days ago it worked fine. So I added `YouTubePlayerView.OnInitializedListener` to print out the `YouTubeInitializationResult` and I got `SERVICE_MISSING`.
Any one could help? thx.

**Comment by 0x12Jung** [comment]
I found that only occurs on Android 11, but still haven't resolve yet..

**Comment by 0x12Jung** [comment]
solution

https://stackoverflow.com/questions/63909770/why-youtube-player-api-does-not-work-on-android-11

add below to manifest
```
<queries>
   <intent>
     <action android:name="com.google.android.youtube.api.service.START" />
   </intent>
</queries>
```

**Comment by ted-prnd** [comment]
@Johnsi1994 
Thanks. this issue will fix at https://github.com/PRNDcompany/YouTubePlayerView/pull/14
