### ISSUE TITLE
How to Show/Hide Disable/Enable controls

### ISSUE THREAD

**Issue by cr4acked** [PRNDcompany/YouTubePlayerView#15]
Hi, nice work done!
I just want to disable video seeking for some reason.
Is it possible to show/hide disable/enable specific control? For example seek bar? 
PlayerStyle.MINIMAL hides all controls except play/pause. This is not what i need.
Thought maybe i can do it with `player.showSeekBar(false)`, but no, there is only `player.setShowFullscreenButton(Boolean)`.
Thanks for answer!

**Comment by ted-prnd** [comment]
@cr4acked 
player class is google's class(not us)
So If player don't have that function, you can not use.
