### ISSUE TITLE
Fullscreen Problem

### ISSUE THREAD

**Issue by JGuideMaster** [PRNDcompany/YouTubePlayerView#16]
This is absolutely a great alternative for Pierfrancesco Soffritti's youtube-player-view. I really love it and already integrated in my application, However I encountered a problem? or not really a bug or a problem but just lack of library feature.

Problem #1
If we integrate this view in a fragment as an item, clicking the fullscreen button will set the device orientation to landscape and sets the height and width to match parent, Unfortunately, it will only fit on the fragment's framelayout that will require another click on the fullscreen button to fully enable fullscreen mode. After this re-clicking the fullscreen button resizes the view but it does not set the device orientation back, so the device is now stucked in landscape even with device's auto rotate, the app won't rotate.

Problem #2 
If we were already on a fullscreen mode with a fragment, clicking back button of the device will completely destroy the whole application, because of this I was opted to use a full activity dedicated in playing youtube videos. It should only toggle off the fullscreen mode by clicking the back button and not close the application. I really hope you update this library as this will definitely be the future of YoutubePlayerViews.

**Comment by ted-prnd** [comment]
@JGuideMaster 
I think your problem seems like this https://github.com/PRNDcompany/YouTubePlayerView/issues/9#issuecomment-659846038

in english

1. Make `isYoutubePlayerFullScreen` boolean field
2. Add `setOnFullscreenListener()` function in YouTubePlayer
```kotlin
setOnFullscreenListener {
    activity?.requestedOrientation =
        if (it) {
            ActivityInfo.SCREEN_ORIENTATION_LOCKED
        } else {
            ActivityInfo.SCREEN_ORIENTATION_USER
        }
    isYoutubePlayerFullScreen = it
}
```
3. When `onBackPressed()`, you can reference `isYoutubePlayerFullScreen` like this
```kotlin
YouTubePlayer youTubePlayer = sellProgressDialog.getYoutubePlayer();
if (youTubePlayer != null) {
    setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_USER);
    youTubePlayer.setFullscreen(false);
}
```

**Comment by JGuideMaster** [comment]
![image](https://user-images.githubusercontent.com/60207682/106401672-5aec3680-6460-11eb-9500-8e9c3d6bfa65.png)

Hi, sorry for the late reply. I wasn't notified about your response. I cannot somehow use the setOnFullscreenListener() function in YouTubePlayer? or Am I missing out something?

**Comment by JGuideMaster** [comment]
Thanks! Super awesome library for youtube!
