### ISSUE TITLE
자동 재생 기능은 사용할 수 없는 것인가요?

### ISSUE THREAD

**Issue by RDH-develop** [PRNDcompany/YouTubePlayerView#5]
안녕하세요. 안드로이드 개발자가 꿈인 학생 입니다.

자동 재생을 하고 싶습니다. 어떤 코드를 추가해야 하나요??
(자바를 사용하고 있어서 코틀린은 이해하지 못하겠습니다..)

**Comment by ted-prnd** [comment]
@RDH-develop 
안녕하세요 우선 이 라이브러리를 사용하시려면 아래에 대한 지식을 먼저 학습하셔야 할것 같습니다.
1. 안드로이드 라이브러리 내 프로젝트에 적용하는 방법
2. YouTube player api 공식 문서 및 샘플 프로젝트 실행

**Comment by couragesuper** [comment]
일단은 이렇게 하니까, 자동재생이 됩니다.  
무식한 방법이니, 정식적인 방법 찾아하세요.

1. 자동재생에 관련된 listener 의 구현에 대한 내용.
https://simsi6.tistory.com/53  
2. YoutubePlayerView.kt의 해당 부분은 구현되어 read-only라서
저는 통째로 복사해서 제 kt 파일을 만들었습니다. 
거기서, play 루틴 밑에 필요한 부분에 다음을 추가했습니다. 

if (!wasRestored) {
                        player.cueVideo(videoId)
                    }

                    **player.setPlayerStateChangeListener(object : YouTubePlayer.PlayerStateChangeListener {
                        override fun onAdStarted() {}
                        override fun onLoading() {}
                        override fun onVideoStarted() {}
                        override fun onVideoEnded() {}
                        override fun onError(p0: YouTubePlayer.ErrorReason) {}
                        override fun onLoaded(videoId: String) { player.play() }
                    })**

                    onInitializedListener?.onInitializationSuccess(provider, player, wasRestored)

listener를 넘기면 될 것 같기도 한데, 아직 kotlin한지 한달 째라 잘 모르겠습니다.

**Comment by couragesuper** [comment]
play하실 떄, 인자로 다음과 같이 listener를 넘겨주시면 됩니다. 

youTubePlayerView.play(song.videoID , object : YouTubePlayerView.OnInitializedListener {
                        override fun onInitializationSuccess(
                            provider: YouTubePlayer.Provider,
                            player: YouTubePlayer,
                            wasRestored: Boolean
                        ){
                            player.setPlayerStateChangeListener(object : YouTubePlayer.PlayerStateChangeListener {
                                override fun onAdStarted() {}
                                override fun onLoading() {}
                                override fun onVideoStarted() {}
                                override fun onVideoEnded() {}
                                override fun onError(p0: YouTubePlayer.ErrorReason) {}
                                override fun onLoaded(videoId: String) { player.play() }
                            })
                        }
                        override fun onInitializationFailure(
                            provider: YouTubePlayer.Provider,
                            result: YouTubeInitializationResult
                        ){}
                    })

**Comment by RDH-develop** [comment]
답변 감사합니다. 해결되었습니다.
