### ISSUE TITLE
상업적 사용에 대하여

### ISSUE THREAD

**Issue by 3Cat-jaguar** [PRNDcompany/YouTubePlayerView#6]
우선 유용한 소프트웨어를 만들고 배포해주심에 감사드립니다.
앱 내에 유튜브 영상이 재생되도록 하는 방법을 찾다가 prnd 에서 만드신 이 뷰를 발견하게 되었습니다.
기존의 방법에 비해 굉장히 쉽게 적용이 되어 유용하게 사용할 수 있을 것 같습니다!
정말 감사합니다!

현재 계획이 확실치 않으나 제가 개발 중인 앱을 무료 배포하지않고 판매를 하게된다면,
(혹은 무료 배포 후 내부 광고 배너를 통해 광고 수익이 발생하게된다면)
내부에 사용된 prnd의 뷰의 저작권 문제가 발생하지 않을까하여 문의드립니다.
깃허브에 올려주신 이 소프트웨어를 상업적 용도의 앱에서도 그냥 사용하여도 괜찮은것인지요?

라이선스(아파치 라이선스 2.0) 부분을 확인하긴했는데...
이렇게 유용한 앱을 그냥 사용해도 괜찮은것인지 하는 생각이 들어... 확인차 여쭙습니다.
다시 한번 감사 인사 드리며 편하실때 답변 부탁드립니다.

**Comment by ted-prnd** [comment]
안녕하세요

라이브러리는 상업적용도로 사용하셔도 아무 문제 없습니다.

다만, 사용중인 오픈소스 라이브러리 메뉴에 해당 라이브러리를 명시해주셔야 합니다.

감사합니다.

**Comment by 3Cat-jaguar** [comment]
답변 감사합니다!!
초보 개발자라 오픈소스 라이브러리 명시해야하는걸 잘 몰랐는데 꼭 명시하도록 하겠습니다!
