### ISSUE TITLE
재생중 화면 뒤로가기 시 음성 표출 잠깐 지속되는 현상

### ISSUE THREAD

**Issue by mjjang88** [PRNDcompany/YouTubePlayerView#8]
우선 해당 오픈소스 제공해주셔서 감사하다는 말씀 드립니다.

재생중 화면 뒤로가기 시 음성 표출이 잠깐 지속되는 현상이 발생하고 있습니다.
뒤로가기 시 재생중인 영상을 Stop 할 수 있게 인터페이스가 필요해 보입니다.

**Comment by ted-prnd** [comment]
@mjjang88 
정확히 어떤 경우인지 잘 모르겠습니다.
현재 샘플 프로젝트에서도 발생하는 이슈인가요?

**Comment by mjjang88** [comment]
@ted-prnd 
샘플 프로젝트에서는 발생하지 않는 것으로 보입니다.
샘플 프로젝트에서는 Fragment의 onPause() 시점에서 영상의 음성이 종료가 되는 것으로 확인이 되는데..
제 프로젝트에서는 YouTubePlayerView가 포함된 Fragment가 완전히 소멸되고 나서 음성이 종료가 되고 있습니다.
JetPack 네비게이션을 사용하여 화면 전환을 하고 있습니다.
음성 종료 시점을 앞당기지 못하면 최악의 경우 영상을 직접 stop 시켜서 음성이 표출되지 않도록 해야 할 것 같아서 문의드렸습니다.

**Comment by mjjang88** [comment]
@ted-prnd 
동적으로 실행하여 Callback으로 YouTubePlayer 가져와서 Fragment 라이프 사이클에서 영상 Pause 처리 했습니다.
감사합니다.
