### ISSUE TITLE
전체화면시 발생되는 이슈

### ISSUE THREAD

**Issue by CKANYWHERE** [PRNDcompany/YouTubePlayerView#9]
안녕하세요 덕분에 라이브러리를 잘 사용하고 있습니다. :)

개발중에 한가지 이슈사항이 있어서 이슈를 등록하게 됩니다.

1. 플레이어 사용중 전체화면 버튼을 누르고 전체화면 버튼을 한번 더 눌러 전체화면을 해제하면 화면이 가로로 고정되어 돌아오지 않는 이슈를 발견 했습니다. 자동 회전으로 바꾸고 돌려봐도 돌려지지가 않네요.

2.전체화면 해제후 플레이 버튼을 누르면 영상이 재생이 잘 되지 않네요..

이 이슈사항들 확인 부탁드립니다..

감사합니다 :)

**Comment by ted-prnd** [comment]
저희도 비슷한 이슈가 있었는데 아래와 같은 방법으로 해결했습니다.


1. Dialog에서 `isYoutubePlayerFullScreen` boolean 변수를 만듭니다.
2. YouTubePlayer에 아래 `setOnFullscreenListener()`를 추가해줍니다
```kotlin
setOnFullscreenListener {
    activity?.requestedOrientation =
        if (it) {
            ActivityInfo.SCREEN_ORIENTATION_LOCKED
        } else {
            ActivityInfo.SCREEN_ORIENTATION_USER
        }
    isYoutubePlayerFullScreen = it
}
```
3. `onBackPressed()`시점에 `isYoutubePlayerFullScreen`를 참고해서 만약 true이면 아래 코드로 처리합니다.
```kotlin
YouTubePlayer youTubePlayer = sellProgressDialog.getYoutubePlayer();
if (youTubePlayer != null) {
    setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_USER);
    youTubePlayer.setFullscreen(false);
}
```
